### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ajithamp** [andpor/react-native-sqlite-storage-examples#2]
![screenshot_1478530508](https://cloud.githubusercontent.com/assets/20926992/20062075/609d78ec-a528-11e6-8b73-f5da1614da11.png)

hi,
i am using your example.db( https://github.com/andpor/react-native-sqlite-storage-examples/blob/master/PrepopulatedDatabaseExample/www/example.db ) and index.android.js code, but i am getting above error any solution for this.

**Comment by andpor** [comment]
@itinance ?

**Comment by itinance** [comment]
This is a common error, when native libraries are not linked correctly.

@ajithamp have you ran "react-native link" after "npm install"?

Try this:

```
cd /tmp
git clone git@github.com:andpor/react-native-sqlite-storage-examples.git
cd react-native-sqlite-storage-examples/PrepopulatedDatabaseExample
npm install
react-native link
react-native run-android
```

This works very well. Just tested again on my machine.

**Comment by ajithamp** [comment]
thanks a lot it works fine

**Comment by ajithamp** [comment]
constructor(props) {
    super(props)

```
this.state = {
  record: null
}   
```

 let db = SQLite.openDatabase({ name: 'test.db' }, this.successCB, this.errorCB); //this part is working  
   db.transaction((tx) => {                                                                                                       <-- //this part is not working in my app
      tx.executeSql('SELECT \* FROM test', [], (tx, results) => {
        alert("Query completed");
        var len = results.rows.length;
        for (let i = 0; i < len; i++) {
          let row = results.rows.item(i);
          alert(`Record: ${row.name}`);
          this.setState({ record: row });
        }
      });
    });                <--//upto  @here
}
errorCB(err) {
    alert("SQL Error: " + err);
  }

  successCB() {
    alert("SQL executed fine");
  }

  openCB() {
    alert("Database OPENED");
  }
